name: Deploy Docker Image

on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  yagdactyl-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
          submodules: true

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
      
      - name: Send Restart Request
        # You may pin to the exact commit or the version.
        # uses: fjogeleit/http-request-action@8e939c608aea2d5df19da3e8229cf035f7aa9e4c
        uses: fjogeleit/http-request-action@v1.8.1
        with:
          # Request URL
          url: ${{ secrets.PANEL_URL }}
          # Request Method
          method: POST
          # Content Type
          contentType: application/json
          # Request Body as JSON String
          data: '{"signal": "restart"}'
          # Bearer Authentication Token
          bearerToken: ${{ secrets.PANEL_API_KEY }}
      - name: Webhook Notification
        uses: johnnyhuy/actions-discord-git-webhook@v1.0.0
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
